services:
  php:
    image: php:8.3.14-apache
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html/

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
      MYSQL_DATABASE: todo
      MARIADB_ROOT_PASSWORD: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
